name: mambamil
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-survival
  - lifelines
  - h5py
  - tqdm
  - tensorboard
  - tensorboardx
  - pip
